"""Build the Columbus per-area geography table: land area and a centroid.

Split out from scrape_acs_columbus.py because this half needs **no API key**.
The Census Gazetteer is a plain TSV bulk download, so land area and centroids
are reproducible by anyone who checks the repo out, while the ACS demographics
behind them are not.

That split matters practically: it lets scrape_weather_columbus.py run today,
and it keeps one source of truth for each area's centroid instead of having the
weather scraper and the ACS scraper each derive their own.

Centroids are LAND-AREA weighted, not population weighted. Weather is a
spatially smooth field and the areas are a few miles across, so the two
centroids differ by less than the resolution of the reanalysis grid -- and the
area-weighted version needs no ACS call, which keeps this file keyless.

Output: Data/Columbus Influenza Data/columbus_area_geography.csv (17 rows).

    python Code/scrapers/scrape_gazetteer_columbus.py
"""

from __future__ import annotations

import argparse
import io
import sys
import zipfile
from pathlib import Path

import pandas as pd
import requests

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from influenza import paths
from influenza.loaders import columbus_crosswalk as crosswalk

GAZETTEER_URL = (
    "https://www2.census.gov/geo/docs/maps-data/data/gazetteer/"
    "{year}_Gazetteer/{year}_Gaz_zcta_national.zip"
)
DEFAULT_YEAR = 2023
TIMEOUT = 120


def fetch_gazetteer(year: int) -> pd.DataFrame:
    """Per-ZCTA land area (sq mi) and internal point. No API key required."""
    response = requests.get(GAZETTEER_URL.format(year=year), timeout=TIMEOUT)
    response.raise_for_status()
    with zipfile.ZipFile(io.BytesIO(response.content)) as archive:
        name = next(n for n in archive.namelist() if n.endswith(".txt"))
        with archive.open(name) as handle:
            frame = pd.read_csv(handle, sep="\t", dtype={"GEOID": str}, encoding="latin-1")
    frame.columns = [c.strip() for c in frame.columns]
    frame["zcta"] = frame["GEOID"].astype(str).str.zfill(5)
    return frame.set_index("zcta")[["ALAND_SQMI", "INTPTLAT", "INTPTLONG"]].rename(
        columns={"ALAND_SQMI": "land_sqmi", "INTPTLAT": "lat", "INTPTLONG": "lon"})


def aggregate_to_areas(gazetteer: pd.DataFrame, zip_area: dict[int, str]) -> pd.DataFrame:
    mapping = pd.Series({f"{z:05d}": area for z, area in zip_area.items()}, name="area")
    joined = gazetteer.join(mapping, how="inner")

    expected = len(zip_area)
    if len(joined) != expected:
        missing = sorted(set(mapping.index) - set(gazetteer.index))
        raise RuntimeError(
            f"Only {len(joined)} of {expected} crosswalk ZIPs have a Gazetteer row. "
            f"Missing: {missing}. A ZIP with no ZCTA has no land area, so pop_density "
            f"for its area would be silently wrong."
        )

    weights = joined["land_sqmi"]
    weighted = joined.assign(_w=weights,
                             _wlat=joined["lat"] * weights,
                             _wlon=joined["lon"] * weights).groupby("area")[
        ["_w", "_wlat", "_wlon"]].sum()
    return pd.DataFrame({
        "land_sqmi": joined.groupby("area")["land_sqmi"].sum(),
        "lat": weighted["_wlat"] / weighted["_w"],
        "lon": weighted["_wlon"] / weighted["_w"],
        "n_zips": joined.groupby("area").size(),
    }).sort_index()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--year", type=int, default=DEFAULT_YEAR)
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()
    output = args.output or (paths.COLUMBUS_DIR / "columbus_area_geography.csv")

    zip_area = crosswalk.zip_to_area()
    print(f"Crosswalk: {len(zip_area)} ZIPs -> {len(set(zip_area.values()))} areas")
    print(f"Gazetteer {args.year}...")
    gazetteer = fetch_gazetteer(args.year)
    print(f"  {len(gazetteer):,} ZCTAs nationally")

    geography = aggregate_to_areas(gazetteer, zip_area)

    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, "w") as handle:
        handle.write(
            f"# Columbus per-area geography. Generated by Code/scrapers/"
            f"scrape_gazetteer_columbus.py\n"
            f"# Source: Census {args.year} Gazetteer, ZCTA national file (no API key needed).\n"
            f"# Centroids are LAND-AREA weighted means of the constituent ZCTA internal\n"
            f"# points. Total land area exceeds Franklin County's ~540 sq mi because\n"
            f"# several ZCTAs extend past the county line -- which is the right\n"
            f"# denominator here, since the ILI extract counts residents of those same\n"
            f"# ZIPs rather than residents of the county.\n")
        geography.to_csv(handle)

    print(f"\n{len(geography)} areas -> {paths.display(output, paths.ROOT)}")
    print(f"Total land area: {geography['land_sqmi'].sum():.1f} sq mi")
    print(geography.round(4).to_string())


if __name__ == "__main__":
    main()
